# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maven (Java) configuration
  - package-ecosystem: "maven"
    directory: "/backend" # Location of pom.xml
    schedule:
      interval: "weekly"

  # npm (JavaScript) configuration for frontend-react
  - package-ecosystem: "npm"
    directory: "/frontend-react" # Ubicación del archivo package.json
    schedule:
      interval: "weekly"

  # npm (JavaScript) configuration for frontend-angular
  - package-ecosystem: "npm"
    directory: "/frontend-angular" # Ubicación del archivo package.json
    schedule:
      interval: "weekly"

  # npm (JavaScript) configuration for frontend-vue
  - package-ecosystem: "npm"
    directory: "/frontend-vue" # Ubicación del archivo package.json
    schedule:
      interval: "weekly"
