name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        directory: ['frontend-angular', 'frontend-react', 'frontend-vue']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./${{ matrix.directory }}/package-lock.json
    - name: Check directory
      run: |
        if [ ! -d "./${{ matrix.directory }}" ]; then
          echo "Directory does not exist: ${{ matrix.directory }}"
          exit 1
        fi
    - run: npm ci --legacy-peer-deps
      working-directory: ./${{ matrix.directory }}
    - run: npm run build --if-present
      working-directory: ./${{ matrix.directory }}
