name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci --legacy-peer-deps
      working-directory: ./frontend-angular
    - run: npm run build
      working-directory: ./frontend-angular

  build-react:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci --legacy-peer-deps
      working-directory: ./frontend-react
    - run: npm run build
      working-directory: ./frontend-react

  build-vue:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci --legacy-peer-deps
      working-directory: ./frontend-vue
    - run: npm run build
      working-directory: ./frontend-vue
