name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [frontend-angular, frontend-react, frontend-vue]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm install --force
      working-directory: ./${{ matrix.directory }}
    - run: npm run build
      working-directory: ./${{ matrix.directory }}
    - run: |
          npm audit || EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            echo "npm audit found vulnerabilities."
          else
            echo "npm audit found no vulnerabilities."
          fi
      working-directory: ./${{ matrix.directory }}
