name: OWASP Dependency Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run OWASP Dependency Check
      run: mvn dependency-check:check -f backend/pom.xml -Dnvd.api.key=${{ secrets.NVD_API_KEY }}
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v2.2.4
      with:
        name: dependency-check-report
        path: backend/target/dependency-check-report.html